trigger:
- Main

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Python38:
      pythonVersion: '3.8'
    Python39:
      pythonVersion: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(pythonVersion)
    addToPath: true

- script: |
    python -m venv env
    source env/bin/activate || exit 1
    pip install --upgrade pip
    pip install --no-cache-dir -r requirements.txt
  displayName: 'Install dependencies'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifactName: 'drop'
    publishLocation: 'container'

- script: |
    deactivate
    rm -rf env
  displayName: 'Deactivate and cleanup'
